
-- DIRTY READS

-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRAN
	SELECT * FROM Donator
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Donator
COMMIT TRAN