USE S9;

-- problem
-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRAN
	SELECT * FROM InghetatePreferate
	WAITFOR DELAY '00:00:10'
	SELECT * FROM InghetatePreferate
COMMIT TRAN