-- non-repeatable reads

Use Playlist;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	SELECT * FROM Melodie
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Melodie
COMMIT TRAN;